one more time

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -98,12 +98,13 @@ jobs:
       - uses: ./.github/actions/setup-node
       - name: Build and pack
         id: build
+        shell: bash
         run: |
           # print packages
           echo 'publishing ${{needs.changesets.outputs.publishedPackages}}'
 
           # convert published packages to "--filter package1 --filter package2"
-          $PUBLISHED_PACKAGES_FILTER=$(echo '${{needs.changesets.outputs.publishedPackages}}' | jq -r '.[] | " --filter " + "\"" + .name+ "\""' | xargs)
+          PUBLISHED_PACKAGES_FILTER=$(echo '${{needs.changesets.outputs.publishedPackages}}' | jq -r '.[] | " --filter " + "\"" + .name+ "\""' | xargs)
 
           # call build scripts - if you have packages with prepublishOnly scripts, call them here too or switch them to build
           pnpm -r $PUBLISHED_PACKAGES_FILTER build
@@ -187,7 +188,7 @@ jobs:
           tar -xf packages.tar
           cd packages
           for pkg in *.tgz; do
-            pnpm publish --tag $TAG --no-git-checks $pkg || { echo "publishing $pkg failed"; FAILED=true; }"
+            pnpm publish --access public --tag $TAG --no-git-checks $pkg || { echo "publishing $pkg failed"; FAILED=true; }"
           done
           if [[ "$FAILED" == "true" ]]; then
             echo "one or more packages failed to publish"
