quotes erat demonstrandum

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -182,12 +182,13 @@ jobs:
           if [[ -f .changeset/pre.json ]]; then
             TAG=$(jq -r '.tag' .changeset/pre.json)
           else
+            # use a different tag here if you publish an older major from a separate branch
             TAG=latest
           fi
           tar -xf packages.tar
           cd packages
           for pkg in *.tgz; do
-            pnpm publish --access public --tag $TAG --no-git-checks $pkg || { echo "publishing $pkg failed"; FAILED=true; }"
+            pnpm publish --access public --tag $TAG --no-git-checks $pkg || { echo "publishing $pkg failed"; FAILED=true; }
           done
           if [[ "$FAILED" == "true" ]]; then
             echo "one or more packages failed to publish"
